create table LOCALIZAPESSOA (
    codpes int not null,
    nompes varchar(120) null,
    tipvin varchar(30) null,
    tipvinext varchar(30) null,
    sitatl char(1) null,
    nomfnc varchar(60) null,
    codundclg smallint null, 
    numtelfmt varchar(40) null,
    sglclgund char(20) null, 
    nomset varchar(255) null,
    nomabvset char(15) null,
    codfncetr int not null,
    codema smallint null,
)