SELECT DISTINCT 
  COLEGIADO.codclg,
  COLEGIADO.sglclg,
  COLEGIADO.nomclg,
  COLEGIADO.tipclg

FROM PARTICIPANTECOLEG
  INNER JOIN COLEGIADO 
    ON (COLEGIADO.codclg = PARTICIPANTECOLEG.codclg AND COLEGIADO.sglclg = PARTICIPANTECOLEG.sglclg)

WHERE COLEGIADO.codundrsp IN (__unidades__)
  AND PARTICIPANTECOLEG.dtafimmdt > :dtafimmdt

ORDER BY COLEGIADO.tipclg, COLEGIADO.nomclg
